Fix missing header
Summary:
Fixes
```
fbcode/deeplearning/projects/wav2letter/recipes/joint_training_vox_populi/cpc/TransformerCPC.cpp:116:16: error: no member named 'sqrt' in namespace 'std'
  q = q / std::sqrt(float(q.dims(1) / nHeads_));
          ~~~~~^
```

Reviewed By: meyering

Differential Revision: D41666017

fbshipit-source-id: dc5333ba990cbdf17bd07b314b394a014aef147d