Fixes missing header
Summary:
Fixes
```
fbcode/deeplearning/projects/wav2letter/recipes/joint_training_vox_populi/cpc/TransformerCPC.cpp:116:16: error: no member named 'sqrt' in namespace 'std'
  q = q / std::sqrt(float(q.dims(1) / nHeads_));
          ~~~~~^
```

Differential Revision: D41666017

fbshipit-source-id: 2a47583fc951a65988b4f40e1f0d14525fa077a0